---

# Importing variables to use for instances
- name: Import - Subnet & SG Variables
  import_role:
    name: vpc
  vars:
    database_subnet_a: database_subnet_a.subnet.id
    database_subnet_b: database_subnet_b.subnet.id
    database_sg_id: database_sg.group_id


- name: Create DB subnet group
  community.aws.rds_subnet_group:
    state: present
    name: subnet_group
    description: Subnet Group for two DB subnets
    subnets:
      - database_subnet_a.subnet.id
      - database_subnet_b
  register: subnet_group

- name: Output - Subnet Group
  set_fact:
    subnet_group: "{{ subnet_group.group_id }}"

- name: Create - Ansible MySQL Instance
  community.aws.rds:
    command: create
    instance_name: AnsibleDB
    db_engine: MySQL
    port: 3306
    publicly_accessible: false
    instance_type: db.t2.micro
    username: admin
    password: password
    subnet: "{{ subnet_group.group_id }}"
    security_groups: "{{ database_sg.group_id }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: ansible_rds