---

- name: Create - Ansible MySQL Instance
  community.aws.rds:
    command: create
    instance_name: AnsibleDB
    db_engine: MySQL
    port: 3306
    size: 20
    publicly_accessible: false
    instance_type: db.t2.micro
    username: admin
    password: password
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  register: ansible_rds