---
- name: Import VPC info
  import_role:
    name: vpc
  vars:
    public_subnet_a: public_subnet_a.subnet.id
    public_subnet_b: public_subnet_b.subnet.id
    public_sg_id: public_sg.group_id

- name: Create Haproxy server
  ec2:
    key_name: "{{webserver_key_name}}"
    instance_type: "{{ instance_type }}"
    image: ""
    vpc_subnet_id: "{{ public_subnet_a.subnet.id }}"
    group_id: "{{ public_sg.group_id }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{ aws_secret_key}}"
    assign_public_ip: yes
    exact_count: 1
    count_tag:
      Name: HAPROXY
