---
- name: Install nginx
  hosts: webserver
  become: yes

  tasks:

  - name: Install epel
    yum_repository:
      name: epel-release
      description: epel
      state: present
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  - name: Install nginx
    yum_repository:
      name: nginx
      description: Nginx repository
      state: present
      baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
