# Install Nginx using Ansible
# Start and Enable Nginx
# Check the status of Nginx
---
- hosts: _Prod
  remote_user: ubuntu
  become: yes
  vars_files:
   - vars.yml
  vars:
   ansible_ssh_private_key_file: "web.pem"
  tasks:
    - name: install httpd
      package:
        name: "httpd"
        state: present

    - name: document root directory
      file:
       state: directory
       dest: "var/www/project"
       
    - name: configure web server
      template:
        dest: /etc/httpd/conf.d/project.conf
        src: templates/localconf.conf.j2

    - name: clone web page
      get_url:
       dest: "/var/www/project"
       url: "https://raw.githubusercontent.com/kierannolan442/webapp/main/index.html"

   - name: service httpd
     service:
       name: "httpd"
       state: started
