# Install Nginx using Ansible
# Start and Enable Nginx
# Check the status of Nginx
---
- hosts: _Prod
  remote_user: ubuntu
  become: yes
  vars_files:
   - vars.yml
  vars:
   ansible_ssh_private_key_file: "web.pem"
  tasks:

   - name: install apache2
     apt: name=apache2 update_cache=yes state=latest

   - name: Create document root
     file:
       path: "/var/www/{{ http_host }}"
       state: directory
       mode: '0775'

   - name: Copy index page j2
     template:
       src: "apache/index.html.j2"
       dest: "/var/www/{{ http_host }}/index.html"

   - name: Copy index page
     template:
       src: "apache/index.html"
       dest: "/var/www/html/index.html"
   - name: Set up VirtualHost
     template:
       src: "apache/apache.conf.j2"
       dest: "/etc/apache2/sites-available/{{ http_conf }}"
     notify: restart-apache

   - name: Port firewall
     ufw:
       rule: allow
       port: "{{ http_port }}"
       proto: tcp

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
