- name: Basic mysql provisioning example
  community.aws.rds:
    command: create
    instance_name: Project Database
    db_engine: MySQL
    size: 20
    instance_type: db.t2.micro
    username: admin
    password: password
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"