---

- name: Install latest version of Nginx
  command: amazon-linux-extras install nginx1.12=latest -y
  args:
    create: /sbin/nginx


- name: Start nginx
  services:
    name: nginx
    state: started

- name: Enable Nginx
  services:
    name: nginx
    enabled: yes

- name: Get Nginx version
  command: nginx -v

- name: Get Nginx status
  command: systemctl status nginx


  
