---


- name:               Create the Ansible VPC
  ec2:
    key_name:               "{{ key_name }}"
    instance_type:               "{{ instance_type }}"
    image:               "{{ image }}"
    wait:               yes
    region:               "{{ region }}"           
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
  register: project_ec2