---
# Importing subnet variables to use for instances
- name: Import - Subnet Variables
  import_role:
    name: vpc
  vars:
    public_subnet_a: public_subnet_a.subnet.id
    public_subnet_b: public_subnet_b.subnet.id        




#Webserver instances
- name: Create Availability Zone A Webserver
  ec2:
    key_name: "{{ webserver_key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    vpc_subnet_id: "{{ public_subnet_a.subnet.id }}"
    wait: yes
    region: "{{ aws_region }}"           
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip: yes
    exact_count: 1
    count_tag:
       Name: webserverA
    instance_tags:
       Name: webserverA
       Environment: Prod
  register: project_web_a

- name: Create Availability Zone B webserver
  ec2:
    key_name: "{{ webserver_key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    vpc_subnet_id: "{{ public_subnet_b.subnet.id }}"
    wait: yes
    region: "{{ aws_region }}"           
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip: yes
    exact_count: 1
    count_tag:
       Name: webserverB
    instance_tags:
       Name: webserverB
       Environment: Prod
  register: project_web_b
