---
- name:               Import Variables from VPC playbook
  import_role:
    name: vpc
  vars:
    public_subnet_a: public_subnet_a.subnet.id
    public_subnet_b: public_subnet_b.subnet.id          

- name:               Create the Ansible EC2 Instances
  ec2:
    key_name:               "{{ key_name }}"
    instance_type:               "{{ instance_type }}"
    image:               "{{ image }}"
    vpc_subnet_id:               "{{ public_subnet_a.subnet.id }}"
    wait:               yes
    region:               "{{ aws_region }}"           
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    instance_tags:
       name: webserver
  register: project_ec2_a

- name:               Create the Ansible VPC
  ec2:
    key_name:               "{{ key_name }}"
    instance_type:               "{{ instance_type }}"
    image:               "{{ image }}"
    vpc_subnet_id:               "{{ public_subnet_b.subnet.id }}"
    wait:               yes
    region:               "{{ aws_region }}"           
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    instance_tags:
       name: webserver
  register: project_ec2_b

- name: Add new instance to host group
            add_host:
                    hostname: "{{ item.public_ip }}"
                    groupname: webserver
            loop: "{{ ec2.instances }}"
          - name: Wait for SSH to come up
            wait_for:
                    host: "{{ item.public_dns_name }}"
                    port: 22
                    state: started
            loop: "{{ ec2.instances }}"